ppwstory/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('story1.urls')),
    path('', include('story3.urls')),
    path('course/', include('story5.urls')),
    path('activity/', include('story6.urls')),
    path('moreinfo/', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('dashboard/', include('story9.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

story9/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("No Email")
        if not username:
            raise ValueError("No Username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_Label):
        return True

story9/forms.py
from django import forms
from .models import MyUser

class CustomUserCreationForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ('email', 'username','password1', 'password2')

    email = forms.EmailField(label="", widget=forms.EmailInput(
        attrs = {
                "id" : "email_sign",
                "class" : "form-input",
                "placeholder" : "Email",
                }
    ))
    username = forms.SlugField(label="", widget=forms.TextInput(
        attrs = {
                "id" : "username_sign",
                "class" : "form-input",
                "placeholder" : "Username",
                }
    ))
    password1 = forms.CharField(label='', widget=forms.PasswordInput(
        attrs = {
                "id" : "pass_1",
                "class" : "form-input",
                "placeholder" : "Password",
                }
    ))
    password2 = forms.CharField(label='', widget=forms.PasswordInput(
        attrs = {
                "id" : "pass_2",
                "class" : "form-input",
                "placeholder" : "Konfirmasi Password",
                }
    ))

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class CustomAuthenticationForm(forms.Form):
    # username = forms.SlugField(label="", widget=forms.TextInput(
    #     attrs = {
    #             "id" : "username_sign",
    #             "class" : "form-input",
    #             "placeholder" : "Username",
    #             }
    # ))
    email = forms.EmailField(label="", widget=forms.EmailInput(
        attrs = {
                "id" : "email_sign",
                "class" : "form-input",
                "placeholder" : "Email",
                }
    ))
    password = forms.CharField(label='', widget=forms.PasswordInput(
        attrs = {
                "id" : "password_sign",
                "class" : "form-input",
                "placeholder" : "Password",
                "autocomplete" : "true",
                }
    ))

    class Meta:
        fields = ['email', 'password']

story9/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as django_login, authenticate as django_authenticate, logout as django_logout
from .forms import CustomUserCreationForm, CustomAuthenticationForm

def dashboard(request):
    return render(request, 'story9/dashboard.html')

def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/dashboard')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            raw_password = form.cleaned_data['password1']
            user = django_authenticate(username=email, password=raw_password)
            django_login(request, user)
            return HttpResponseRedirect('/dashboard')
    else:
        form = CustomUserCreationForm()
    return render(request, 'story9/register.html', {'form': form})

def login(request):
    messages = []
    if request.user.is_authenticated == True:
        return HttpResponseRedirect('/dashboard')
    if request.method == 'POST':
        form = CustomAuthenticationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = django_authenticate(username=email, password=password)
            if user:
                if user.is_active:
                    django_login(request, user)
                    return HttpResponseRedirect('/dashboard')
            messages.append('Email atau password salah!')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'story9/login.html', {'form': form, 'messages': messages})
    
@login_required
def logout(request):
    django_logout(request)
    return HttpResponseRedirect('/dashboard')

story9/templates/story9/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Dashboard</title>
<link rel="stylesheet" href="{% static 'story9/css/style.css' %}">
{% endblock meta %}

{% block content %}
<div class="main text-center">
    {% if user.is_authenticated %}
    <h2>Selamat Datang <span>{{ user.username }}</span>!</h2>
    <h5>Email yang terdaftar: {{ user.email }}</h5>
    <a href="{% url 'story9:logout' %}" class="btn-user btn-lg m-2">Log Out</a>
    {% else %}  
    <h2>Silakan Log In terlebih dahulu :D</h2>
    <a href="{% url 'story9:login' %}" class="btn-user btn-lg m-2">Log In</a>
    <a href="{% url 'story9:register' %}" class="btn-user btn-lg m-2">Register</a>
    {% endif %}
</div>
{% endblock content %}

story9/templates/story9/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
<title>Login - Dashboard</title>
<link rel="stylesheet" href="{% static 'story9/css/style.css' %}">
{% endblock meta %}

{% block content %}
<div class="main text-center">
  <div class="section">
      <h2>Log <span>In</span></h2>
      {% if messages %}
        <ul class="messages">
            {% for message in messages %}
              <li style="color:red">{{ message }}</li>
            {% endfor %}
        </ul>
      {% endif %}
      <form action="{% url 'story9:login' %}" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <p>Belum punya akun?</p>
        <a href="{% url 'story9:register' %}">Register</a>
        <input class="btn-submit" type="submit" value="Log In">
      </form>
    </div>
</div>
{% endblock content %}

story9/templates/story9/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
<title>Register - Dashboard</title>
<link rel="stylesheet" href="{% static 'story9/css/style.css' %}">
{% endblock meta %}

{% block content %}
<div class="main text-center">
  <div class="section">
    <h2><span>Register</span></h2>
    <form action="{% url 'story9:register' %}" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <p>Sudah punya akun?</p>
        <a href="{% url 'story9:login' %}">Log In</a>
        <input class="btn-submit" type="submit" value="Register">
    </form>
  </div>
</div>
{% endblock content %}