ppwstory/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('story1.urls')),
    path('', include('story3.urls')),
    path('course/', include('story5.urls')),
    path('activity/', include('story6.urls')),
    path('moreinfo/', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('dashboard/', include('story9.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.activity, name="activity"),
    path('save_activity', views.save_activity, name="save_activity"),
    path('add_person/<int:id>', views.add_person, name="add_person"),
    path('delete_activity/<int:id>', views.delete_activity, name="delete_activity"),
    path('delete_person/<int:id>', views.delete_person, name="delete_person"),
]

story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    name = models.CharField(max_length=30)
    desc = models.TextField()

    def __str__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=30)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

story6/forms.py
from django import forms
from .models import Activity, Person

class Input_Form(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['name', 'desc']

        name_attr = {
            'type': 'text',
            'placeholder': 'Activity name',
        }
        desc_attr = {
            'type': 'text',
            'placeholder': 'Add description here . . .'
        }

        labels = {
            'name': 'Activity',
            'desc': 'Description'
        }

        widgets = {
            'name': forms.TextInput(attrs=name_attr),
            'desc': forms.Textarea(attrs=desc_attr)
        }


class Person_Form(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['name']

        labels = {
            'name': ''
        }

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Your name', 'class': 'person-add'})
        }

story6/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import Input_Form, Person_Form
from .models import Activity, Person

# Create your views here.
def activity(request):
    response = {
        'input_form': Input_Form,
        'activity_list': Activity.objects.all(),
        'person_list': Person.objects.all(),
        'person_form': Person_Form
    }
    return render(request, 'story6/activity.html', response)

def save_activity(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        value = request.POST['name']
        messages.success(request, f'Activity {value} has been added!')
    else:
        form = Input_Form()
    return HttpResponseRedirect('/activity#activity')

def add_person(request, id):
    form = Person_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        value = request.POST['name']
        activity_obj = get_object_or_404(Activity, pk=id)
        Person.objects.create(name=value, activity=activity_obj)
        messages.success(request, f'{value} has been added to {activity_obj.name}.')
    return HttpResponseRedirect('/activity#activity')

def delete_activity(request, id):
    if (request.method == 'POST'):
        activity_obj = get_object_or_404(Activity, pk=id)
        messages.success(request, f'Activity {activity_obj} has been deleted!')
        activity_obj.delete()
    return HttpResponseRedirect('/activity#activity')

def delete_person(request, id):
    if (request.method == 'POST'):
        person_obj = get_object_or_404(Person, pk=id)
        messages.success(request, f'{person_obj} has been deleted from {person_obj.activity}.')
        person_obj.delete()
    return HttpResponseRedirect('/activity#activity')

story6/templates/story6/activity.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
    <title>Activity Add | List</title>
{% endblock meta %}

{% block content %}
    <div class="form">
        <div class="form-section">
            <h2 align="center">Activity Add <span>Form</span></h2>
            <hr class="orange-line">
            <form action="save_activity" method="POST">
                {% csrf_token %}
                {{ input_form|crispy }}
                <input class="btn-submit" type="submit" value="Submit">
            </form>
        </div>
    </div>
    {% if activity_list %}
        <div id="activity" class="activity">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <h2 align="center">Activity <span>List</span></h2>
            <hr class="orange-line">
            <div class="row justify-content-center">
                {% for activity in activity_list %}
                    <div class="col-sm-4 col-sm-offset-0 course-section">
                        <div class="row">
                            <div class="col">
                                <h4>{{ activity.name }}</h4>
                                <form action="{% url 'story6:delete_activity' activity.id %}" method="POST" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn-delete-activity"><b>Delete</b></button>
                                </form>
                                <p><em>{{ activity.desc }}</em></p>
                            </div>
                        </div>
                        <hr color="lightgrey" style="margin-top: 3px;">
                        <b>Participant:</b>
                        <ul class="person-list">
                            {% for person in person_list %}
                                {% if person.activity == activity %}
                                    <li>{{ person.name }}
                                        <form action="{% url 'story6:delete_person' person.id %}" method="POST" style="display: inline;">
                                            {% csrf_token %}
                                            <button type="submit" class="btn-delete-person"><b>x</b></button>
                                        </form>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                        <form action="{% url 'story6:add_person' activity.id %}" method="POST">
                            {% csrf_token %}
                            <div class="row justify-content-left">
                                <div class="col">
                                    {{ person_form }}
                                    <button type="submit" class="btn-add">Add</button>
                                </div>
                            </div>
                        </form>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock content %}