ppwstory/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('story1.urls')),
    path('', include('story3.urls')),
    path('course/', include('story5.urls')),
    path('activity/', include('story6.urls')),
    path('moreinfo/', include('story7.urls')),
    path('books/', include('story8.urls')),
    path('dashboard/', include('story9.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.course, name="course"),
	path('saveform', views.saveform, name="saveform"),
	path('details/<int:id>', views.details, name="details"),
	path('delete/<int:id>', views.delete, name="delete"),
]

story5/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=30)
    lecturer = models.CharField(max_length=50)
    credit = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(24)
        ]
    )
    desc = models.TextField()
    term = models.CharField(max_length=30)
    room = models.CharField(max_length=30)

    def __str__(self):
        return self.name

story5/forms.py
from django import forms
from .models import Course

class Input_Form(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'lecturer', 'credit', 'desc', 'term', 'room']

        name_attr = {
            'type': 'text',
            'placeholder': 'Course name',
        }
        lecturer_attr = {
            'type': 'text',
            'placeholder': 'Lecturer\'s name'
        }
        credit_attr = {
            'placeholder': 'Credits count'
        }
        desc_attr = {
            'type': 'text',
            'placeholder': 'Add description here . . .'
        }
        term_attr = {
            'type': 'text',
            'placeholder': 'ex. Gasal 2019/2020'
        }
        room_attr = {
            'type': 'text',
            'placeholder': 'Room location of the course'
        }

        widgets = {
            'name': forms.TextInput(attrs=name_attr),
            'lecturer': forms.TextInput(attrs=lecturer_attr),
            'credit': forms.NumberInput(attrs=credit_attr),
            'desc': forms.Textarea(attrs=desc_attr),
            'term': forms.TextInput(attrs=term_attr),
            'room': forms.TextInput(attrs=room_attr)
        }

        labels = {
            'name': 'Course',
            'lecturer': 'Lecturer',
            'credit': 'Credits',
            'desc': 'Description',
            'term': 'Term',
            'room': 'Room'
        }

story5/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import Input_Form
from .models import Course

# Create your views here.
def course(request):
    response = {
        'input_form': Input_Form,
        'courses': Course.objects.all()
    }
    return render(request, 'story5/course.html', response)

def details(request, id):
    course_obj = get_object_or_404(Course, pk=id)
    course_response = {
        'course': course_obj
    }
    return render(request, 'story5/details.html', course_response)

def delete(request, id):
    course = get_object_or_404(Course, pk=id)
    course.delete()
    messages.success(request, f'Course has been deleted!')
    return HttpResponseRedirect('/course')

def saveform(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        messages.success(request, f'Course added to list!')
    else:
        form = Input_Form()
        messages.warning(request, f'Credit must be between 1 and 24!')
    return HttpResponseRedirect('/course')

story5/templates/story5/course.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
    <title>Course Add | List</title>
{% endblock meta %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="form">
        <div class="form-section">
            <h2 align="center">Course Add <span>Form</span></h2>
            <hr class="orange-line">
            <form action="saveform" method="POST">
                {% csrf_token %}
                {{ input_form|crispy }}
                <input class="btn-submit" type="submit" value="Submit">
            </form>
        </div>
    </div>
    {% if courses %}
        <div id="course" class="activity">
            <h2 align="center">Course <span>List</span></h2>
            <hr class="orange-line">
            <div class="row">
                {% for course in courses %}
                    <div class="col-sm-4 col-sm-offset-0 course-section">
                        <div class="row">
                            <div class="col">
                                <h4>{{ course.name }}</h4>
                                <a href="{% url 'story5:details' course.id %}">Details</a>
                            </div>
                        </div>
                        <hr color="lightgrey">
                        <ul>
                            <li><b>Lecturer:</b> {{ course.lecturer }}</li>
                            <li><b>Description:</b> {{ course.desc }}</li>
                        </ul>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock content %}

story5/templates/story5/details.html
{% extends "base.html" %}
{% load static %}

{% block meta %}
    <title>Course: {{ course.name }}</title>
{% endblock meta %}

{% block content %}
    <div class="details">
        <div class="details-section">
            <div class="details-title">
                <h2 align="center">{{ course.name }}</h2>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Lecturer</b>
                </div>
                <div class="col-sm-6 col -sm-6-offset-0 value">
                    {{ course.lecturer }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Credit</b>
                </div>
                <div class="col-sm-6 col-sm-6-offset-0 value">
                    {{ course.credit }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Description</b>
                </div>
                <div class="col-sm-6 col-sm-6-offset-0 value">
                    {{ course.desc }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Term</b>
                </div>
                <div class="col-sm-6 col-sm-6-offset-0 value">
                    {{ course.term }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-6-offset-0 key">
                    <b>Room</b>
                </div>
                <div class="col-sm-6 col-sm-6-offset-0 value">
                    {{ course.room }}
                </div>
            </div>
            <div class="row" align="center">
                <div class="col m-4">
                    <a href="/course" class="btn-back">Back</a>
                    <a href="{% url 'story5:delete' course.id %}" class="btn-delete">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}